### ISSUE TITLE
Memory leak in ResonanceAudioSource.DrawDirectivityGizmo

### ISSUE THREAD

**Issue by pschraut** [resonance-audio/resonance-audio-unity-sdk#1]
_ResonanceAudioSource.DrawDirectivityGizmo_ is creating a new Mesh every frame, if the ResonanceAudioSource GameObject is selected.

This causes memory to grow as long as the GameObject is selected while the editor is play-mode. Memory is only released when exiting play-mode.

**Reproduce**
- Open example scene _ResonanceAudioDemo_
- Open Window > Profiler from Unity's main menu
- Click "Add Profiler" in Profiler window toolbar and select "Memory"
- Click "Record" button in Profiler window toolbar
- Press Edit > Play
- Press Window > Scene to switch to Scene window while it's playing
- Select "Cube" in Hierarchy panel
Observe in the Unity Profiler window that "Meshes memory" grows as well as "Total object count".

**Expected**
Selecting the ResonanceAudioSource GameObject should not cause a memory leak.

**Comment by anokta** [comment]
Thanks for catching this, Peter! And your detailed bug report is very much appreciated!

This will be fixed in the next release.

**Comment by anokta** [comment]
Fixed in [v1.1.0](https://github.com/resonance-audio/resonance-audio-unity-sdk/releases/tag/v1.1.0).
