### ISSUE TITLE
Updating SDK overrides material mappings

### ISSUE THREAD

**Issue by reekdeb** [resonance-audio/resonance-audio-unity-sdk#11]
Currently updating the Resonance Audio SDK overrides `ResonanceAudioMaterialMapper.asset`. Updating SDK should retain material mappings or should provide a way to save material mappings asset at custom location to prevent overrides.

**Comment by anokta** [comment]
Good point, thanks for the suggestion! We will look into this to improve upon such scenarios.

**Comment by anokta** [comment]
Fixed in [v1.2.0](https://github.com/resonance-audio/resonance-audio-unity-sdk/releases/tag/v1.2.0).
