### ISSUE TITLE
Reverb Probe list is not scrollable in Reverb Baking window

### ISSUE THREAD

**Issue by reekdeb** [resonance-audio/resonance-audio-unity-sdk#13]
Reverb Probe list should be scrollable. When there are large number of Reverb Probes in a scenes the  `Bake` button and material mappings are invisible in Reverb Baking window.

**Comment by mgorzel** [comment]
Many thanks for reporting the issue @reekdeb, we will have a look!

**Comment by anokta** [comment]
Fixed in [v1.2.0](https://github.com/resonance-audio/resonance-audio-unity-sdk/releases/tag/v1.2.0).
