### ISSUE TITLE
Not working with Unity 2017.3.0f3?

### ISSUE THREAD

**Issue by AlexGareauV10** [resonance-audio/resonance-audio-unity-sdk#14]
Hi, two weeks ago, I ask about a import problem I had with Resonance and Unity ( See:  #12 )

But now, I wonder, if that possible that the soundfield (or entire sdk) does not work in Unity 2017.3? 
Actually, on iOs, I had to update the pods manually via the terminal to make the sdk working (or else it crashed when mixed with VR, weird boringssl error), but on Android no luck so far. 

Using:
Unity 2017.3.0f3
Resonance Audio SDK for Unity v1.1.1

I get those errors in Android Device Monitor (But only when building from : Unity 2017.3.0f3)

> Unable to find libaudiopluginresonanceaudio
> 
> Audio effect Resonance Audio Renderer could not be found. 
> Check that the project contains the correct native audio plugin
> libraries and that the importer settings are set up correctly.
> 

In Unity 2017.2, everythings worked perfectly!

**Comment by anokta** [comment]
Thanks for reporting, Alex! We will take a look at it.

Just to verify again, does the issue exist when using a new Unity project (as described in the previous issue #12)?

**Comment by AlexGareauV10** [comment]
Thanks for the support!

I tried with a new Unity project, added Resonance Audio, added a soundfield prefab, added an ambisonic sound (voice_o1_ambix from the answer in #12 ) and when tested on the device, the sound is not spatialized.

As I said, on iOs I had to udpate the cocoa pods via the terminal, so maybe some part of the sdk has not been updated on Android too?

**Comment by anokta** [comment]
Hi Alex,

Thanks for the additional information! I was able to reproduce the issue as stated. It seems to be an Android platform specific problem that was introduced in Unity 2017.2.1 (and above). 

We're currently investigating the issue further with Unity to find out the root cause. In the meantime, I'd suggest to downgrade the Unity version you're using back to 2017.2.0 (or below) as a temporary workaround. Will keep this thread updated.

**Comment by fredsa** [comment]
For details, see Unity case # [988299](https://issuetracker.unity3d.com/issues/android-ios-audiosource-playing-through-google-resonance-audio-sdk-with-spatializer-enabled-does-not-play-on-built-player).

**Comment by mauskopf** [comment]
Unity has released patches that fix this issue that affected 2017.2.1f1+, which I've verified on 2017.3.1p1.

https://unity3d.com/unity/qa/patch-releases
