### ISSUE TITLE
No sound after first scene load (Unity 2017.3.0f3 / SDK v1.1.1)

### ISSUE THREAD

**Issue by mages-gamedev** [resonance-audio/resonance-audio-unity-sdk#15]
Hi,

I noticed in our project ResonanceAudio plays fine on the first scene when built to Android (music set to loop and play on awake). However, after loading to any other scene, there will be no more sound from any ResonanceAudio components (whether loop or invoked). Running in-editor is working as intended, this issue only arises when previewing from mobile devices.

I proceeded to test with the Resonance sample unitypackage v1.1.1 and implemented a quick scene reload function. Same result - no sound after any scene load (tested with both async and non-async scene loads).

Unity Version: Unity 2017.3.0f3
ResonanceAudioSDK Version: Resonance Audio SDK for Unity v1.1.1

I appreciate your time in looking into this issue. It's a show-stopper for us now...

**Comment by anokta** [comment]
Thanks for reporting the issue! We will have a look shortly.

**Comment by anokta** [comment]
Hi,

Could you verify if the issue is observable in Unity 2017.2.0f3 (or below)? 

FYI, we are currently investigating a potentially related issue specific to Android builds that affects Unity 2017.2.1f1 (and above) users. Please refer to the issue #14 for further details.

**Comment by mages-gamedev** [comment]
Hi anokta,

We've followed your suggestion to downgrade the project to 2017.2.0f3 (or below) and can confirm that it fixes both the audio cutting and crash in-editor that was referred to in #10. Specifically, we have used Unity 2017.2.0f3 for this and after a couple of tries and tweaks, it does not crash anymore nor give us broken audio when run from a compiled .apk.

Thanks for the suggestion!
