### ISSUE TITLE
Baking window locks up the editor in project with a lot of mateirals. 

### ISSUE THREAD

**Issue by wrstscrnnm6** [resonance-audio/resonance-audio-unity-sdk#16]
I am running Unity 2017.2.0f3 and downloaded SDK 1.1.1
I could run the test scenes fine. I could create Reverb probes and adjust their position etc. without any trouble. When I go to open the reverb baking window, everything grinds to a halt. CPU use shoots up and the editor frame rate falls to <1FPS. 
 
This project has 595 materials in it. I suspected that was the root of the issue. After digging around in with the editor profiler. I found:

- `ResonanceAudioAcousticMesh.GenerateFromMeshFilter()` was allocating ~98.2MB every other frame
- `ResonanceAudioReverbBakingWindow.DrawMaterialMappingGUI()` was allocating ~14.5MB (it looks like most of that was caused by `AssetPreview.GetAssetPreview()` )

As a test, I disabled the AssetPreview calls in the editor script for the Baking Window and that brought that window from unusable to simply sluggish. 

I don't, of course, know all of how things are implemented under the hood. But I might suggest modifying the workflow a bit to allow the user to select which materials they want to be visible to the reverb baker (e.g. create a new list/array item > select the material > select the acoustic behavior ) rather than auto-mapping every material in the project.

**Comment by anokta** [comment]
Thanks for the suggestion and findings! We will discuss this issue internally to see how we can improve upon the material mapping workflow accordingly.

**Comment by anokta** [comment]
Major improvements in Editor performance with [v1.2.0](https://github.com/resonance-audio/resonance-audio-unity-sdk/releases/tag/v1.2.0). Closing the issue, please feel free to let us know if you have any further concerns.
