### ISSUE TITLE
ResonanceAudioRoomManager generates garbage memory

### ISSUE THREAD

**Issue by pschraut** [resonance-audio/resonance-audio-unity-sdk#2]
ResonanceAudioRoomManager.UpdateRoom() is called by ResonanceAudioRoom(s). The method allocates a RoomEffectsRegion object every call, causing garbage memory to be created.

It's recommended to write per-frame allocation free code, if performance is a concern, such as in interactive applications that have to run at 60 or 90 frames per second. 

**Reproduce**
- Open Resonance Audio Unity SDK 1.0.0 example project in Unity
- Open File > Build Settings...
- Add "ResonanceAudioDemo.unity" to "Scenes in Build" list
- Select Platform "PC, Mac & Linux Standalone"
- Select Target Platform = Windows
- Tick the "Development Build" option
- Press "Build" 
- Run the built player using Windows 10
- Go back to Unity while player continues to run in background
- Open Window > Profiler from Unity's main menu
- In the Profiler toolbar, select running player from the "Connected Players" popup

Observe in "CPU Usage" profiler that ResonanceAudioRoom.Update() allocates 224 bytes every frame. It's tracked in the "GC Alloc" column.

**Expected**
Code that runs every frame should not allocate memory, which causes GC collection eventually.

There are other methods in ResonanceAudioRoomManager that cause GC allocs as well, such as "RemoveRoom". Ideally, these should also cause no allocations.

**Comment by anokta** [comment]
Another great catch, Peter! We're currently looking into this. Should be fixed by the next update.

Thanks!

**Comment by ilmarioranen** [comment]
I'd like to also point out that this also creates 56b per-frame GC alloc overhead. Noticed with with deep profiling (tested with Editor playmode, not actual build yet):
  AudioSettings.GetSpatializerPluginName()

String concat or such, maybe? Should be avoidable allocations.

**Comment by anokta** [comment]
Fixed in [v1.1.0](https://github.com/resonance-audio/resonance-audio-unity-sdk/releases/tag/v1.1.0).
