### ISSUE TITLE
Fatal error if a gameobject doesn't have an assigned mesh

### ISSUE THREAD

**Issue by BountyVSGames** [resonance-audio/resonance-audio-unity-sdk#23]
When an object has a mesh renderer and mesh filter but it doesn't have an assigned mesh, then that object will give a null reference once the editor window of resonance audio is opened.

This is important because we have a multi-VR setup that uses the boundary for the VR setup and it is not generated yet. This could be a common issue that others might face as well.

Maybe as a suggestion, you could add a Debug.LogWarning at the ResonanceAudioAcousticMesh.GeneratefromMeshFilter() that there is no mesh assigned.

**Comment by mgorzel** [comment]
Thanks for reporting that and for your suggestion @BountyVSGames! We are looking into that and will get back to you soon!

**Comment by anokta** [comment]
Fixed in [v1.2.1](https://github.com/resonance-audio/resonance-audio-unity-sdk/releases/tag/v1.2.1).
