### ISSUE TITLE
WebGL export issue

### ISSUE THREAD

**Issue by charlifiiiii** [resonance-audio/resonance-audio-unity-sdk#26]
Hi,
Using Resonance 1.2.0 and Unity 2017.4.0f1, everything works fine in the Unity project, however it does not seem to work when exporting the Unity project as a webGL application. Is this supported ?

This is the error message I get in the Firefox console :
Audio effect Resonance Audio Renderer could not be found. Check that the project contains the correct native audio plugin libraries and that the importer settings are set up correctly.
Audio source is playing an ambisonic audio clip, but an ambisonic decoder could not be created successfully. Make sure an ambisonic decoder is selected in the audio settings.

Thanks

**Comment by mauskopf** [comment]
Export to WebGL is not supported or planned at this time.

FYI The Unity plugin is open source so one option is implementing WebGL export support yourself, and we could review your changes if you'd like to contribute back to the project: https://github.com/resonance-audio/resonance-audio

There is also a Resonance Audio SDK for the Web that's separate from Unity, if that's of interest: https://github.com/resonance-audio/resonance-audio-web-sdk
