### ISSUE TITLE
ResonanceAudioSource.OnEnable generates garbage memory

### ISSUE THREAD

**Issue by pschraut** [resonance-audio/resonance-audio-unity-sdk#4]
Many Unity applications use a _GameObject Pooling_ strategy to improve performance, see [use object pooling](https://unity3d.com/learn/tutorials/topics/performance-optimization/optimizing-scripts-unity-games).

That is, GameObject's are (re)used multiple times during a level or application lifetime. If a GameObject isn't needed, it gets deactivated and put in a pool. If the game later asks for that GameObject, it's retrieved from the pool and activated again. I use pooling for effects and sounds a lot for example.

When activating/deactivating a GameObject, the OnEnable() and OnDisable() methods of all Components on that GameObject are called.

The issue with _ResonanceAudioSource.OnEnable_ is that 'mixer.FindMatchingGroups' allocates memory, which would cause an application, that uses a pooling strategy, to generate garbage memory during run-time.

**Expected**
Enabling/Disabling a ResonanceAudioSource should not allocate memory aka GC.Alloc and OnEnable/OnDisable should be kept fast.

**Comment by mauskopf** [comment]
Thanks for reporting this, Peter! 

We'll look into this suggestion. Thanks for the helpful explanation!

**Comment by anokta** [comment]
Fixed in [v1.1.0](https://github.com/resonance-audio/resonance-audio-unity-sdk/releases/tag/v1.1.0).
