### ISSUE TITLE
C API

### ISSUE THREAD

**Issue by RobotCaleb** [resonance-audio/resonance-audio-unity-sdk#5]
Is there a C API for Resonance somewhere? I only see integrations.

**Comment by jkammerl** [comment]
For [Android](https://developers.google.com/vr/android/ndk/reference/group/audio) and [iOS](https://developers.google.com/vr/ios/reference/interface_g_v_r_audio_engine) we published a C API as part of the GVR SDK (which can also be independently used from GVR).

**Comment by RobotCaleb** [comment]
Are they suitable for inclusion in non Android or iOS projects?
